### ISSUE TITLE
Support for alternative zoom links (i.e. redirects created by booking apps)

### ISSUE THREAD

**Issue by entreprenewer** [quicksilver/zoom.us#1]
Hi Rob! (I finally found this area on Github, but only after emailing you directly. Sorry about that).

I love the Zoom plugin, but I have one suggestion.

Some “calendar scheduling” apps have implemented a redirect link because of some of Zoom’s new security features, so the calendar link that they generate looks like this, for example:

https://app.acuityscheduling.com/schedule.php?owner=131***962&action=zoom&uniqueID=0cd***fff3e0a826b4f8de40dbaae76f&ownerID=*****

Alternatively, some people may have their own custom links, like I do (https://mywebsite.com/zoom or http://zoomwithnick.com).

I would propose that you update the code to look for ANY link with the word “Zoom” in it, not just an official Zoom link.

I would do this myself, but alas, I have almost 0 programming skills whatsoever.

Thanks!

**Comment by skurfer** [comment]
Yes, I’ve been trying to update it because we use custom URLs where I work and more and more meetings are including passwords in the link, which the original version of the plug-in didn't support. I’ve mostly got it working. The one remaining hurdle is a meeting with a name instead of a numeric ID, like “https://site.zoom.us/my/allhands”. The `zoommtg` URL scheme doesn’t seem to support those.

> I would propose that you update the code to look for ANY link with the word “Zoom” in it, not just an official Zoom link.

The whole point of this plug-in is to convert the HTTP link to a `zoommtg://` URL so you don’t have to bring your browser to the front for no reason and get left with a useless tab open.

For the meetings that redirect, I assume they’re redirecting to the HTTP URL and not the `zoommtg` one, so the plug-in won’t be able to do its magic. For that case, it probably makes more sense to add a generic “Open Meeting URL” action to the Calendar plug-in.

**Comment by entreprenewer** [comment]
Interesting - yeah, you’re right, I hadn’t realized that THAT was the magic you’re doing, because I rarely ever get non-redirect meeting URLs. 

I’ll reach out to acuity and see what can be done, if anything. 

I’ll also see if I can figure out how to manipulate the calendar module. 

Thanks for the speedy reply, you’re a legend.

**Comment by skurfer** [comment]
> I’ll also see if I can figure out how to manipulate the calendar module.

If you’re going to take that on, this should help.

http://projects.skurfer.com/QuicksilverPlug-inReference.mdown#actions

The Calendar plug-in needs to be updated to use EventKit, but I don’t have time. For now, you can look at the Zoom plug-in for more modern code that pulls the URL out of an event but there are no events currently in the catalog, so you’d have to add them to run the action on them.

My long term plan was to:

1. Update the Calendar plug-in to add events to the catalog using EventKit.
2. Update the Zoom plug-in to work with the events in the catalog, instead of scanning the calendars itself.
3. Tell the Zoom plug-in to require the Calendar plug-in on installation.

So if you’re super bored, that would be the ideal outcome and would set you up nicely to create the new action. (Actually, you could just let the existing “Open URL” action do the work by adding a URL type to events in the catalog.)

**Comment by entreprenewer** [comment]
Yikes - this went way over my head unfortunately. Alas, I wish I were a developer - a skill I could never get excited about :( 


Thanks anyways!
JL

--

Jonathan Levi
Founder | SuperHuman Enterprises, LLC.
https://superhumanacademy.com/ <https://superhumanacademy.com/>
P.S. I generally handle emails on Mondays and Thursdays only. Thanks for your patience.
 <http://fb.com/jonathanleviofficial>	 <http://jle.vi/youtube>	 <http://instagram.com/jonathanalevi>	 <http://twitter.com/jonathanalevi>
P.P.S. I would be honored if you'd let me gift you a free copy of my latest book – just cover the shipping and handling at http://freelearningbook.com <http://freelearningbook.com/>
 <http://freelearningbook.com/>

#noauto

**Comment by entreprenewer** [comment]
By the way, how come I’m getting “large type” even when I do have a real zoom link… any ideas why?




Thanks,
JL

--

Jonathan Levi
Founder | SuperHuman Enterprises, LLC.
https://superhumanacademy.com/ <https://superhumanacademy.com/>
P.S. I generally handle emails on Mondays and Thursdays only. Thanks for your patience.
 <http://fb.com/jonathanleviofficial>	 <http://jle.vi/youtube>	 <http://instagram.com/jonathanalevi>	 <http://twitter.com/jonathanalevi>
P.P.S. I would be honored if you'd let me gift you a free copy of my latest book – just cover the shipping and handling at http://freelearningbook.com <http://freelearningbook.com/>
 <http://freelearningbook.com/>

#noauto

**Comment by skurfer** [comment]
> By the way, how come I’m getting “large type” even when I do have a real zoom link… any ideas why?

It must not be finding the meeting URL. When it can’t find one, the proxy object refers to the text “No Upcoming Meeting” instead.

**Comment by skurfer** [comment]
I’ve updated the Zoom plug-in to handle some of the new features:

* vanity URLs like mycompany.zoom.us
* vanity meeting IDs
* meeting URLs with additional arguments (like a password)

Like I said, other arbitrary URLs are probably best handled outside this plug-in.
